nomecliente = input("Digite o nome do cliente: ")
diavencimento = input("Digite o dia de vencimento: ")
mesvencimento = input("Digite o mês de vencimento: ")
valorfatura = input("Digite o valor da fatura: ")
print (f"Olá, {nomecliente}\nA sua fatura com vencimento em {diavencimento} de {mesvencimento} no valor de R$ {valorfatura} está fechada.")